logging:
    level:
        ROOT: INFO
        com.wondertek.cmam: INFO
        io.github.jhipster: INFO
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker
eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@management-registry:8761/eureka/
    instance:
        appname: ${spring.application.name}
        instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.context-path}/info
        health-check-url-path: ${management.context-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version}
        prefer-ip-address: true
ribbon:
    eureka:
        enabled: true
management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: managementuaa
    profiles:
        active: prod
        include: swagger
    jackson:
        serialization.write_dates_as_timestamps: false
        serialization.indent_output: true
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false 
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.1.3:13306/cmamUaa?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
        cache-seconds: 1
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
        cache: false
    mail:
        host: localhost
        port: 25
        username:
        password:
    zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
        base-url: http://localhost:9411
        enabled: false
        locator:
            discovery:
                enabled: true
    redis:
        host: 192.168.1.12
        port: 6379
        password:
        timeout: 3000
        pool:
            maxActive: 500
            maxIdle: 300
            maxWait: 2000
security:
    basic:
        enabled: false
    oauth2:
        resource:
            filter-order: 3

server:
    port: 9999
    session:
        cookie:
            http-only: true
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

info:
    project:
        version: v0.0.1

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: http://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
    swagger:
        default-include-pattern: /(api|user|group|operation|permission|role)/.*
        title: managementUaa API
        description: managementUaa API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    ribbon:
        display-on-active-profiles: dev
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        client-authorization:
            client-id: internal
            client-secret: internal
        authentication:
            jwt:
                # Access Token is valid for 5 mins
                token-validity-in-seconds: 300
                # Refresh Token is valid for 7 days
                token-validity-in-seconds-for-remember-me: 252000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: managementUaa@localhost
        base-url: http://127.0.0.1:9999
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite: # Use the "graphite" Maven profile to have the Graphite dependencies
            enabled: false
            host: localhost
            port: 2003
            prefix: managementUaa
        prometheus: # Use the "prometheus" Maven profile to have the Prometheus dependencies
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
uaa:
    key-store:
        name: keystore.jks
        password: password
        alias: selfsigned
    web-client-configuration:
        # Access Token is valid for 5 mins
        access-token-validity-in-seconds: 300
        # Refresh Token is valid for 7 days
        refresh-token-validity-in-seconds-for-remember-me: 604800
        client-id: web_app
        secret: changeit
rbacSecurity:
    ignore-url:
#        - /api/register
#        - /api/activate
#        - /api/authenticate
#        - /api/account/reset-password/init
#        - /api/account/reset-password/finish
        - /api/profile-info
#        - /user/**
#        - /role/**
#        - /group/**
#        - /operation/**
#        - /permission/**
        - /api/**
        - /management/health
        - /management/**
        - /v2/api-docs/**
        - /swagger-resources/configuration/ui
        - /swagger-ui/index.html
        - /oauth/token_key
        - /oauth/token
    app-name: managementuaa
    base-url: http://managementuaa
application:
